### ISSUE TITLE
How do you test the model accuracy? + Check points are not stored correctly 

### ISSUE THREAD

**Issue by iNuraj** [shaohua0116/SSGAN-Tensorflow#12]
I see the model outputs the following: 
Supervised loss, D loss, G loss, Accuracy, and test loss. 
Is this the training accuracy or test accuracy? if it's the training accuracy how could we get the test accuracy? 
Is it using evaler.py? because I run the model on a dummy dataset and got an accuracy of ~ 80% but when I run the evaluator I got an accuracy of ~ 1.5% which does not seem correct. 

Also, when I try to run the evaler.py from a checkpoint, none of the files saved during training can be used when referencing them. I am attaching a photo of the files generated during the training. 
![train_dir](https://user-images.githubusercontent.com/9090335/31666056-9a29e868-b353-11e7-8941-8fe7796d0f60.png)
Thanks in advance.

**Comment by ahasanpour** [comment]
Dear  iNuraj
It seems you could run the model. could you please come to [this issue](https://github.com/gitlimlab/SSGAN-Tensorflow/issues/8) and say what is your configuration?

Thank you.

**Comment by shaohua0116** [comment]
Please specify the path to the checkpoint like `python evaler.py --checkpoint /path/to/ckpt/model-1`.

**Comment by shaohua0116** [comment]
And please make sure your model save the checkpoints frequently enough so that when you want to test the model, there are stored checkpoints instead of just the first checkpoint `model-1`.
