### ISSUE TITLE
Are unlabeled images used in SSGAN?

### ISSUE THREAD

**Issue by CassieMai** [shaohua0116/SSGAN-Tensorflow#13]
In paper "Improved techniques for training GANs", models are trained and compared on different number of labeled images. However, in your code, there is no settings about the number of labeled images or unlabeled images. So did you consider to use various number of labeled images in training? @shaohua0116

**Comment by JacksonHacker** [comment]
@CassieMai Have you disposed of this problem? I also want to utilize unlabeled data in the semi-supervised training process.

**Comment by LuShuaie** [comment]
Dear author,
I didn't find unlabeled settings in your code, could you tell me where you set up the unlabeled settings?
thanks

**Comment by shaohua0116** [comment]
Thank you for pointing this out. Now the numbers of images that are used for training the generator can be change here https://github.com/gitlimlab/SSGAN-Tensorflow/blob/1323a53f02503caa28b67e1ee52a4c30252a51dd/datasets/hdf5_loader.py#L65

**Comment by ronghuiju** [comment]
I also want to know if this program could process unlabeled data, thanks

**Comment by WayneDW** [comment]
Yeah, the problem is still not solved.
