### ISSUE TITLE
Number of labelled samples per class

### ISSUE THREAD

**Issue by deeplimbo** [shaohua0116/SSGAN-Tensorflow#15]
Hi, I might be wrong but I didn't find that part of the code where you just select a subset of labelled samples for supervision and the rest are all unlabelled. I think this is the semi-supervised part of the paper. In case I have missed, can you point out where this is implemented in your code? Thanks

**Comment by shaohua0116** [comment]
Please change the code [here](https://github.com/gitlimlab/SSGAN-Tensorflow/blob/1323a53f02503caa28b67e1ee52a4c30252a51dd/datasets/hdf5_loader.py#L65) to specify how many labeled images you want to use to train the generator.

**Comment by WayneDW** [comment]
This means in your README file, you used as many as 56000 labeled images?
