### ISSUE TITLE
why the _groundtruths in the evaler.py is different from the original test label?

### ISSUE THREAD

**Issue by B-Xi** [shaohua0116/SSGAN-Tensorflow#18]
Dear Sun，
Thanks for your code，
As for the SVHN datasets, I printed the  feeded groundtruth in the evaler.py in a .txt file, and why are they different from the original test labe in the .mat filel? And I run the evaler.py for many times, and I printed the  feeded groundtruth for each time, they are different from each other.

**Comment by shaohua0116** [comment]
SVHN uses the labels from 1 to 10 and my code converts them to 0 to 9. Sorry for the confusion.
