### ISSUE TITLE
AttributeError: 'Trainer' object has no attribute 'pretrain_saver'

### ISSUE THREAD

**Issue by alphamupsiomega** [shaohua0116/SSGAN-Tensorflow#2]

**Comment by shaohua0116** [comment]
Fixed it. Please clone it again & thanks for reporting the issue.

**Comment by alphamupsiomega** [comment]
Didn't work yet.  Error:

>
>[2017-06-12 19:51:05,583] Checkpoint path: train_dir/default-MNIST_lr_0.0001_update_G5_D1-20170612-194957/checkpoint
>2017-06-12 19:51:05.663582: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open train_dir/default-MNIST_lr_0.0001_update_G5_D1-20170612-194957/checkpoint: Data loss: not an sstable >(bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

**Comment by shaohua0116** [comment]
Please specify the checkpoint dir like:
```train_dir/default-MNIST_lr_0.0001_update_G5_D1-20170612-194957/model-1001```

**Comment by shaohua0116** [comment]
Please specify the checkpoint for like:
train_dir/default-MNIST_lr_0.0001_update_G5_D1-20170612-194957/model-1001

**Comment by alphamupsiomega** [comment]
Works now.  Thank you.  Would be helpful to add this to the documentation since model-1001 is not itself an actual file, but just part of a filename.

**Comment by shaohua0116** [comment]
Thank you for your suggestion. Just added it to README.
