### ISSUE TITLE
Something error in the code tf.train.exponential_decay

### ISSUE THREAD

**Issue by wangguanan** [shaohua0116/SSGAN-Tensorflow#4]
I think the first parameter of the funciton [tf.train.exponential_decay] should be a constant(learing_rate_start) instead of self.learning_rate, which is a variable and will lead to unexpected fast decrease, because after running the function you assign the decayed self_learning_rate to self.learning_rate as a initial learning_rate again. 
Although this part code was not used in your model, it's better to point out the hidden danger。

![image](https://user-images.githubusercontent.com/18496599/28238011-275d48fe-697d-11e7-8063-31b374323fc9.png)

**Comment by shaohua0116** [comment]
Actually, this is not an error and there's no fast decrease.
