### ISSUE TITLE
The discriminator should be trained more times ...

### ISSUE THREAD

**Issue by junwang929** [shaohua0116/SSGAN-Tensorflow#5]
Hi @shaohua0116, thanks for your nice job! 
However, I think one thing should be noticed, the discriminator should be trained more times than the generator.  
After I change your code in the 'trainer.py' as follows:
![wechatimg67](https://user-images.githubusercontent.com/25918824/29299995-7a6d7a2a-8127-11e7-9c74-c6d234abe6bf.jpeg)
the prediction accuracy improves quite a lot! 
Hope you can notice~
thank you!

**Comment by shaohua0116** [comment]
Please note that there's a trade-off between training the classifier faster and training the generator well so that the generated samples are able to help improve the generalization of the classifier.
