### ISSUE TITLE
How to generate samples?

### ISSUE THREAD

**Issue by douglas01996** [shaohua0116/SSGAN-Tensorflow#6]
How to generate samples?

**Comment by shaohua0116** [comment]
If you want to keep generating samples along the training process, just use the argument `--dump_result`. If you want to generate samples while testing trained models, you can simply fetch `self.model.fake_img`.

**Comment by douglas01996** [comment]
After generating samples along the training process, how to use visualize_training.py to create gif?

**Comment by shaohua0116** [comment]
Taking CIFAR10 for example, use the command `python visualize_training .py --h 32 --w 32 --c 3 --n 8 --output_file visualized_sample --train_dir train_dir/default-CIFAR10_lr_0.0001_update_G5_D1-20170101-194957`

**Comment by douglas01996** [comment]
Thank you for your quick reply!
