### ISSUE TITLE
Where is the generated image stored?

### ISSUE THREAD

**Issue by taki0112** [shaohua0116/SSGAN-Tensorflow#7]
Where is the generated image stored?

I'm learning cifar10, can not I create images while learning?

**Comment by taki0112** [comment]
```bash
python trainer.py --dataset CIFAR10 --dump_result True
```

is not working...

I would like to save it as an image. (not gif)
is it possible ?

**Comment by taki0112** [comment]
```bash
python trainer.py --datset CIFAR10 --dump_result
```
is working

but...
```bash
python visualize_training.py --output_file visualized_sample --train_dir train_dir/default-CIFAR10~~~
```

is ***not*** *working*

***Could not find a format to write the specified file in mode 'I'*** in *visualize_training.py, line 31*
```python
imageio.mimsave(args.output_file, II, fps=5)
```

**Comment by shaohua0116** [comment]
If `--dump_result` is specified, the generated images would be stored in the training directory in the hdf5 file format (`.hy`).

**Comment by shaohua0116** [comment]
Can you provide all the commands you tried to visualize the training? Also, please provide the detailed information including how many iterations you ran, etc.

**Comment by zlpsls** [comment]
python visualize_training.py --output_file visualized_sample --train_dir train_dir/default-MNIST_lr_0.0001_update_G5_D1-20180707-162149 --h 28 --w 28 --c 1 --n 8

is not working

  File "visualize_training.py", line 26, in <module>
    I[args.h*i:args.h*(i+1), args.w*j:args.w*(j+1), :] = f[f.keys()[0]][i*args.n+j,:,:,:]
TypeError: 'KeysView' object does not support indexing

**Comment by zlpsls** [comment]
python visualize_training.py --output_file visualized_sample --train_dir train_dir/default-MNIST_lr_0.0001_update_G5_D1-20180707-195643 --h 28 --w 28 --c 1

Traceback (most recent call last):
  File "visualize_training.py", line 31, in <module>
    imageio.mimsave(args.output_file, II, fps=5)
  File "/usr/local/lib/python2.7/dist-packages/imageio/core/functions.py", line 320, in mimwrite
    writer = get_writer(uri, format, 'I', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/imageio/core/functions.py", line 170, in get_writer
    'in mode %r' % mode)
ValueError: Could not find a format to write the specified file in mode 'I'
