### ISSUE TITLE
errors when I try two separate data.hy files 

### ISSUE THREAD

**Issue by heimanba89** [shaohua0116/SSGAN-Tensorflow#9]
Hi, 

When I try to change the script, and add an option to read train and test files from two different filenames, like:
def create_dataset(dataset_1,dataset_2,id_1,id_2,is_train=True):
    ids_train = all_ids_train(id_1)
    ids_test = all_ids_train(id_2)

    dataset_train = Dataset(ids_train, dataset_1, name='train', is_train=False)
    dataset_test  = Dataset(ids_test, dataset_2, name='test', is_train=False)
    return dataset_train, dataset_test
I got the error:
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_0_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 16, current size 4)

I tested with single file and split the data.hy solution, it is good, my problem is the single data.hy file is too big to generate. 

Any ideas?
Thanks,
Chunlei

**Comment by shaohua0116** [comment]
Please pull the new code. The issue should be resolved now.
